---
- name: Testing cluster status
  shell: mysql -u root -p{{ mysql_root_password }} -e "SHOW STATUS LIKE 'wsrep_cluster_size'" | grep 'wsrep_cluster_size' | awk '{print $2}'
  when: inventory_hostname == groups['mysql_cluster'][0]
  run_once: true
  register: cluster_status

- name: Test status
  debug:
      msg:
         - " Test connection successfull"
         - " Total number of active mysql nodes in cluster: '{{ cluster_status.stdout }} '"
         - " Setup Completed!"
  when: inventory_hostname == groups['mysql_cluster'][0]
  run_once: true
