---
- block:
    - name: check etcd cluster health
      run_once: true
      command:  etcdctl cluster-health
      register: etcd_health_result
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"
      changed_when: false

    - name: Etcd Cluster health
      run_once: true
      debug:
        var: etcd_health_result.stdout_lines
  ignore_errors: yes
  tags: etcd_status

- block:
    - name: check postgresql cluster health
      run_once: true
      become: yes
      become_user: postgres
      command: patronictl -c /etc/patroni.yml list
      register: patronictl_result
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"
      changed_when: false

    - name: PostgreSQL Cluster health
      run_once: true
      debug:
        var: patronictl_result.stdout_lines
  ignore_errors: yes
  tags: patroni_status


