---
   
- import_tasks: timezone.yml
  when: timezone is defined and timezone | length > 0
  ignore_errors: yes
  tags: [ timezone, configure ]

- import_tasks: etcd.yml
  tags: [ etcd, etcd_cluster ]

- import_tasks: tasks/add-repository.yml
  tags: [ add_repo ]

- import_tasks: tasks/packages.yml
  tags: [ install_packages ]

- import_tasks: tasks/patroni.yml
  tags: patroni

- import_tasks: tasks/postgresql-extensions.yml
  when: is_master == "true" and postgresql_extensions | length > 0
  tags: postgresql_extensions

# finish (info)
- import_tasks: deploy_finish.yml
  tags: [ cluster_info, cluster_status ]

